### ISSUE TITLE
two-way  all  FAILURE 

### ISSUE THREAD

**Issue by datrilla** [Davipb/utf8-utf16-converter#1]
cd  ./tester/test-cases/ &&./tester utf8    two-way/bible.utf8.txt         two-way/bible.utf16.txt
  line 252  FAILURE expected_len[8704570] output_len[8905032]
UTF-8 to UTF-16
Input: 4 MiB
Output: 8 MiB

**Comment by Davipb** [comment]
This seems to be an issue with automatic newline conversion on Linux, I'll see if I can mark the test case files as binary so git won't try to do anything clever with them.

Thanks for letting me know!

**Comment by Davipb** [comment]
Done, cloning the repo on Linux should preserve the test cases byte-by-byte with no funny business. 

Can you try running the tests again to see if they work properly now? Make sure to delete the folder and clone the repo from scratch, don't just do a pull.

**Comment by datrilla** [comment]
I download  zip，instead of tester ，all test success now

**Comment by Davipb** [comment]
Nice, thanks for the response. I'll close the issue now since everything seems to be in order.
