### ISSUE TITLE
[Not an issue] Thank you for this library (and a new use case)

### ISSUE THREAD

**Issue by lemenkov** [Davipb/utf8-utf16-converter#5]
Hello @Davipb,
I'd like to thank you for this handy library. Just recently I successfully fixed a licensing issue in one of the applications I am using - see twogood/unshield#185 for the details.

Unfortunately there are more unaware users of the problematic old Unicode software license many of then could just switch to your implementation, let's hope they all eventually do

* https://github.com/search?q="This+source+code+is+provided+as+is+by+Unicode%2C+Inc"&type=code

**Comment by Davipb** [comment]
Thank *you* @lemenkov !

I love hearing how people use my projects and seeing where the tiny things I throw into the void of the internet end up. Glad to see it's still being useful!
